language: rust
rust:
  - 1.40.0
stages:
  - name: test
    if: branch != docker-build
  - name: deploy
    if: branch = docker-build

jobs:
  include:
    - stage: test
      name: osx
      os: osx
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '(^spec/|\.md$)'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - nvm install 12
        - nvm use 12
        - npm install -g yarn
      before_script:
        - cargo fetch --verbose
        - cargo build
        - cd test && yarn
      script:
        - yarn start-short
        - yarn start-long
      after_failure:
        - ./upload_logs.sh
    - os: linux
      name: linux
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^spec/|\.md$'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - nvm install 12
        - nvm use 12
        - npm install -g yarn
      before_script:
        - cargo fetch --verbose
        - cargo build
        - cd test && yarn
      script:
        - yarn start-short
        - yarn start-long
      after_failure:
        - ./upload_logs.sh
    - os: linux
      name: dynamic-validator-1
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^spec/|\.md$'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - nvm install 12
        - nvm use 12
        - npm install -g yarn
      before_script:
        - cargo build --verbose
        - cd test && yarn
      script:
        - yarn start-dyn-val-1
      after_failure:
        - ./upload_logs.sh
    - os: linux
      name: dynamic-validator-2
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^spec/|\.md$'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - nvm install 12
        - nvm use 12
        - npm install -g yarn
      before_script:
        - cargo build --verbose
        - cd test && yarn
      script:
        - yarn start-dyn-val-2
      after_failure:
        - ./upload_logs.sh
    - stage: deploy
      name: deploy
      script: skip
      services:
        - docker
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: docker-build
notifications:
  webhooks: https://webhooks.gitter.im/e/71bb03cf9abce5b02c43
cache:
  timeout: 1000
  cargo: true
  directories:
    - "$HOME/.rustup"
    - "$HOME/.cache/yarn"
    - "$TRAVIS_BUILD_DIR/test/node_modules"
before_cache:
  - rm -rf $HOME/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target
git:
  depth: 50
