language: rust
rust:
  - 1.32.0
stages:
  - name: test
    if: branch != docker-build
  - name: deploy
    if: branch = docker-build

jobs:
  include:
    - stage: test
      name: test-osx
      os: osx
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^(docs|spec)/'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^test/'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - rustup toolchain install nightly-2018-12-06
        - rustup component add rustfmt-preview --toolchain nightly-2018-12-06
        - rustup component add clippy-preview --toolchain nightly-2018-12-06
      before_script:
        - cargo fetch --verbose
      script:
        - cargo +nightly-2018-12-06 fmt -- --check || exit 1
        - cargo +nightly-2018-12-06 clippy --all-targets --all-features -- -D warnings || exit 1
        - RUST_BACKTRACE=1 cargo test --verbose --all || exit 1
    - name: int-test-osx
      os: osx
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^(docs|spec)/'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - nvm install 10
        - nvm use 10
        - npm install -g yarn
      before_script:
        - cargo fetch --verbose
      script:
        - cd test && yarn && yarn lint || exit 1
        - cargo build || exit 1
        - INT_TEST_FLAG=true && yarn start-short
        - yarn start-long
      after_failure:
        - test $INT_TEST_FLAG && ./upload_logs.sh
    - name: test-linux
      os: linux
      sudo: false
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^(docs|spec)/'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^test/'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - rustup toolchain install nightly-2018-12-06
        - rustup component add rustfmt-preview --toolchain nightly-2018-12-06
        - rustup component add clippy-preview --toolchain nightly-2018-12-06
      before_script:
        - cargo fetch --verbose
      script:
        - cargo +nightly-2018-12-06 fmt -- --check || exit 1
        - cargo +nightly-2018-12-06 clippy --all-targets --all-features -- -D warnings || exit 1
        - RUST_BACKTRACE=1 cargo test --verbose --all || exit 1
    - name: int-test-linux
      os: linux
      sudo: false
      before_install:
        - SKIP=`.travis/check-mergify-merge` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
        - SKIP=`.travis/check-change '^(docs|spec)/'` && if [[ "$SKIP" = "skip" ]]; then exit 0; fi
      install:
        - nvm install 10
        - nvm use 10
        - npm install -g yarn
      before_script:
        - cargo fetch --verbose
      script:
        - cd test && yarn && yarn lint || exit 1
        - cargo build || exit 1
        - INT_TEST_FLAG=true && yarn start-short
        - yarn start-long
      after_failure:
        - test $INT_TEST_FLAG && ./upload_logs.sh
    - stage: deploy
      name: deploy
      sudo: required
      script: skip
      services:
        - docker
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: docker-build
notifications:
  webhooks: https://webhooks.gitter.im/e/71bb03cf9abce5b02c43
cache:
  timeout: 1000
  cargo: true
  directories:
    - "$HOME/.rustup"
    - "$HOME/.cache/yarn"
    - "$TRAVIS_BUILD_DIR/test/node_modules"
before_cache:
  - rm -rf $HOME/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target
git:
  depth: 50
