language: rust
rust:
  - 1.28.0
stages:
  - name: test
    if: branch != docker-build
  - name: deploy
    if: branch = docker-build
jobs:
  include:
    - stage: test
      name: test-osx
      os: osx
      install:
        - rustup toolchain install nightly-2018-07-17
        - rustup component add rustfmt-preview --toolchain nightly-2018-07-17
      before_script:
        - cargo fetch --verbose
      script:
        - cargo +nightly-2018-07-17 fmt -- --check && RUST_BACKTRACE=1 cargo test --verbose --all
    - name: test-linux
      os: linux
      sudo: required
      install:
        - rustup toolchain install nightly-2018-07-17
        - rustup component add rustfmt-preview --toolchain nightly-2018-07-17
      before_script:
        - cargo fetch --verbose
      script:
        - cargo +nightly-2018-07-17 fmt -- --check && RUST_BACKTRACE=1 cargo test --verbose --all
    - name: test-int-linux
      os: linux
      install:
        - nvm install 8
        - nvm use 8
        - npm install -g yarn
      script:
        - cd test && yarn && yarn start
    - name: test-int-osx
      os: osx
      install:
        - nvm install 8
        - nvm use 8
        - npm install -g yarn
      script:
        - cd test && yarn && yarn start
    - stage: deploy
      name: deploy
      sudo: required
      script: skip
      services:
        - docker
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: docker-build
notifications:
  webhooks: https://webhooks.gitter.im/e/71bb03cf9abce5b02c43
cache: cargo
git:
  depth: 1
