language: rust
rust:
  - 1.30.0
stages:
  - name: test
    if: branch != docker-build
  - name: deploy
    if: branch = docker-build
jobs:
  include:
    - stage: test
      name: test-osx
      os: osx
      install:
        - nvm install 8
        - nvm use 8
        - npm install -g yarn
        - rustup toolchain install nightly-2018-10-18
        - rustup component add rustfmt-preview --toolchain nightly-2018-10-18
        - rustup component add clippy-preview --toolchain nightly-2018-10-18
      before_script:
        - cargo fetch --verbose
      script:
        - cargo +nightly-2018-10-18 fmt -- --check || TEST_FAILED=true
        - test $TEST_FAILED || cargo +nightly-2018-10-18 clippy --all || TEST_FAILED=true
        - test $TEST_FAILED || RUST_BACKTRACE=1 cargo test --verbose --all || TEST_FAILED=true
        - test $TEST_FAILED || cd test && yarn && yarn lint || TEST_FAILED=true
        - test $TEST_FAILED || INT_TEST_FLAG=true && yarn start-release || TEST_FAILED=true
        - "! test $TEST_FAILED"
      after_failure:
        - test $INT_TEST_FLAG && ./upload_logs.sh
    - name: test-linux
      os: linux
      sudo: required
      install:
        - nvm install 8
        - nvm use 8
        - npm install -g yarn
        - rustup toolchain install nightly-2018-10-18
        - rustup component add rustfmt-preview --toolchain nightly-2018-10-18
        - rustup component add clippy-preview --toolchain nightly-2018-10-18
      before_script:
        - cargo fetch --verbose
      script:
        - cargo +nightly-2018-10-18 fmt -- --check || TEST_FAILED=true
        - test $TEST_FAILED || cargo +nightly-2018-10-18 clippy --all || TEST_FAILED=true
        - test $TEST_FAILED || RUST_BACKTRACE=1 cargo test --verbose --all || TEST_FAILED=true
        - test $TEST_FAILED || cd test && yarn && yarn lint || TEST_FAILED=true
        - test $TEST_FAILED || INT_TEST_FLAG=true && yarn start-release || TEST_FAILED=true
        - "! test $TEST_FAILED"
      after_failure:
        - test $INT_TEST_FLAG && ./upload_logs.sh
    - stage: deploy
      name: deploy
      sudo: required
      script: skip
      services:
        - docker
      deploy:
        provider: script
        script: bash docker_push.sh
        on:
          branch: docker-build
notifications:
  webhooks: https://webhooks.gitter.im/e/71bb03cf9abce5b02c43
cache:
  timeout: 1000
  cargo: true
  directories:
    - "$HOME/.rustup"
    - "$HOME/.cache/yarn"
    - "$TRAVIS_BUILD_DIR/test/node_modules"
before_cache:
  - rm -rf $HOME/.cargo/registry
  - rm -rf $TRAVIS_BUILD_DIR/target
git:
  depth: 1
