language: rust
rust:
  - stable
install:
  - rustup toolchain install nightly-2018-05-07
  - rustup component add rustfmt-preview --toolchain nightly-2018-05-07
before_script:
  - cargo fetch --verbose
script:
  - cargo +nightly-2018-05-07 fmt -- --write-mode=diff
  - RUST_BACKTRACE=1 cargo test --verbose --all
matrix:
  allow_failures:
    - rust: nightly
  include:
    - os: linux
      sudo: required
    - os: osx
cache: cargo
