indent_style = "Block"
use_small_heuristics = "Off" # "Default"
binop_separator = "Front"
# combine_control_expr = true
comment_width = 120 # 80
condense_wildcard_suffixes = true # false
control_brace_style = "AlwaysSameLine"
# disable_all_formatting = false
error_on_line_overflow = false # true
# error_on_unformatted = false
fn_args_density = "Tall"
brace_style = "PreferSameLine" # "SameLineWhere"
empty_item_single_line = true
fn_single_line = false
# where_single_line = false
force_explicit_abi = true
format_strings = false
hard_tabs = false
imports_indent = "Block" # "Visual"
imports_layout = "Mixed"
merge_imports = false
match_block_trailing_comma = false
max_width = 120 # 100
merge_derives = true
# force_multiline_blocks = false
newline_style = "Unix"
normalize_comments = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
# reorder_impl_items = false
# report_todo = "Never"
# report_fixme = "Never"
# skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 0
spaces_around_ranges = false
## struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = false # true
# type_punctuation_density = "Wide"
use_field_init_shorthand = true # false
use_try_shorthand = true # false
wrap_comments = false
match_arm_blocks = true
blank_lines_upper_bound = 2 # 1
blank_lines_lower_bound = 0
hide_parse_errors = false
color = "Always" # "Auto"
unstable_features = false
# license_template_path
