[package]
name = "codechain-rpc"
version = "0.1.0"
authors = ["CodeChain <codechain@kodebox.io>"]

[lib]

[dependencies]
codechain-core = { path = "../core" }
codechain-types = { path = "../primitives/codechain-types" }
kvdb = { path = "../util/kvdb" }
kvdb-rocksdb = { path = "../util/kvdb-rocksdb" }
log = "0.4.1"
rlp = { path = "../util/rlp" }
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rustc-hex = "1.0"
rustc-serialize = "0.3"
tokio-core = "0.1.1"
jsonrpc-core = { git = "https://github.com/ethcore/jsonrpc.git" }
jsonrpc-macros = { git = "https://github.com/ethcore/jsonrpc.git" }
jsonrpc-http-server = { git = "https://github.com/ethcore/jsonrpc.git" }

