[package]
name = "codechain-network"
version = "0.1.0"
authors = ["Kodebox <codechain@kodebox.io>"]

[dependencies]
codechain-crypto = { path = "../crypto" }
codechain-finally = { path = "../util/finally" }
codechain-io = { path = "../util/io" }
codechain-keys = { path="../keys" }
codechain-types = { path = "../primitives/codechain-types" }
log = "0.4.1"
mio = "0.6.8"
parking_lot = "0.5"
rand = "0.4"
rlp = { path = "../util/rlp" }
slab = "0.4"
table = { path = "../util/table" }
