[package]
name = "codechain-core"
version = "0.1.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]

[dependencies]
codechain-bytes = { path = "../util/bytes" }
codechain-crypto = { path = "../crypto" }
codechain-io = { path = "../util/io" }
codechain-json = { path = "../json" }
codechain-keys = { path="../keys" }
codechain-types = { path = "../primitives/codechain-types" }
codechain-logger = { path = "../logger" }
hashdb = { path = "../util/hashdb" }
heapsize = "0.4"
log = "0.3"
num_cpus = "1.2"
kvdb = { path = "../util/kvdb" }
kvdb-rocksdb = { path = "../util/kvdb-rocksdb" }
kvdb-memorydb = { path = "../util/kvdb-memorydb" }
memorydb = { path = "../util/memorydb" }
parking_lot = "0.5"
patricia-trie = { path = "../util/patricia_trie" }
rlp = { path = "../util/rlp" }
rlp_compress = { path = "../util/rlp_compress" }
rlp_derive = { path = "../util/rlp_derive" }
time = "0.1"
triehash = { path = "../util/triehash" }
unexpected = { path = "../util/unexpected" }
util-error = { path = "../util/error" }
