[codechain]
quiet = false
db_path = "db"
snapshot_path = "snapshot"
chain = "solo"
secret_key = "0x0000000000000000000000000000000000000000000000000000000000000001"

[mining]

[network]
disable = false
port = 3485
max_peers = 30
min_peers = 10
bootstrap_addresses = []
sync = true
parcel_relay = true

[rpc]
disable = false
port = 8080

