[codechain]
quiet = false
db_path = "db"
snapshot_path = "snapshot"
chain = "solo"
enable_block_sync = true
enable_parcel_relay = true
secret_key = "0x0000000000000000000000000000000000000000000000000000000000000001"
