[codechain]
quiet = false
db_path = "db"
chain = "solo"
secret_key = "0x0000000000000000000000000000000000000000000000000000000000000001"

[mining]

[network]
disable = false
port = 3485
max_peers = 30
min_peers = 10
bootstrap_addresses = []
sync = true
parcel_relay = true
discovery = true
discovery_type = "unstructured"
discovery_refresh = 60000
discovery_bucket_size = 10

[rpc]
disable = false
port = 8080

[ipc]
disable = false
path = "/tmp/jsonrpc.ipc"

[snapshot]
path = "snapshot"
