[package]
name = "codechain-sync"
version = "0.1.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]

[lib]

[dependencies]
codechain-core = { path = "../core" }
codechain-key = { path = "../key", features = ["ecdsa"] }
codechain-logger = { path = "../util/logger" }
codechain-merkle = { path = "../util/merkle" }
codechain-network = { path = "../network" }
codechain-types = { path = "../primitives/codechain-types" }
kvdb = { path = "../util/kvdb" }
log = "0.4.1"
parking_lot = "0.5"
patricia-trie = { path = "../util/patricia_trie" }
rand = "0.5.3"
rlp = { path = "../util/rlp" }
time = "0.1"
triehash = { path = "../util/triehash" }

[dev-dependencies]
codechain-key = { path = "../key", features = ["ecdsa"] }
