[package]
name = "codechain-discovery"
version = "0.1.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]

[dependencies]
codechain-crypto = { path = "../crypto" }
codechain-key = { path="../key" }
codechain-logger = { path = "../util/logger" }
codechain-network = { path = "../network" }
codechain-types = { path = "../primitives/codechain-types" }
log = "0.4.1"
parking_lot = "0.5"
rand = "0.4"
rlp = { path = "../util/rlp" }
time = "0.1"

[dev-dependencies]
lazy_static = "1.0"
