[package]
name = "codechain-timer"
version = "0.1.0"
authors = ["CodeChain Team <codechain@kodebox.io>"]

[lib]

[dependencies]
parking_lot = "0.6.0"
log = "0.4.6"
codechain-logger = { path = "../logger" }
