[package]
name = "codechain-timer"
version = "0.1.0"
authors = ["CodeChain Team <hi@codechain.io>"]
edition = "2018"

[lib]

[dependencies]
parking_lot = "0.11.0"
log = "0.4.6"
codechain-logger = { path = "../logger" }
