on: [push, pull_request]

name: build

jobs:
  build:
    name: Actions - build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-10.14, ubuntu-18.04]
      fail-fast: false
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.40.0
          profile: minimal
          override: true
      - run: cargo fetch --verbose
      - run: cargo build --release
      - name: Archive
        working-directory: target/release
        run: |
          mkdir artifacts
          echo ${{github.sha}} ${{github.ref}} | tee artifacts/git-ref
          shasum -a 256 codechain | tee artifacts/sha256sums
          CODECHAIN_VERSION="$(./codechain --version | cut -d ' ' -f 2)"
          tar cvfz artifacts/codechain-${CODECHAIN_VERSION}-$(uname -m)-$(echo $(uname) | tr '[:upper:]' '[:lower:]').tar.gz codechain
      - uses: actions/upload-artifact@v1
        with:
          name: codechain-${{ matrix.os }}
          path: target/release/artifacts
